// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString},
		{Name: "avatar", Type: field.TypeString, Default: "https://robohash.org/honey?set=set1"},
		{Name: "remind_me", Type: field.TypeBool, Default: true},
		{Name: "wake_up_time", Type: field.TypeTime},
		{Name: "sleep_time", Type: field.TypeTime},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"MALE", "FEMALE"}},
		{Name: "weight", Type: field.TypeFloat32, Default: 50},
		{Name: "daily_intake", Type: field.TypeInt32, Default: 1500},
		{Name: "container_image", Type: field.TypeString, Default: "images/glass-of-water.png"},
		{Name: "container_volume", Type: field.TypeInt32, Default: 300},
		{Name: "drink_at_a_time", Type: field.TypeInt32, Default: 300},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
