// Code generated by entc, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"github.com/ducnguyen96/ducnguyen96.xyz-apis/authservice/ent/schema"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldRemindMe holds the string denoting the remind_me field in the database.
	FieldRemindMe = "remind_me"
	// FieldWakeUpTime holds the string denoting the wake_up_time field in the database.
	FieldWakeUpTime = "wake_up_time"
	// FieldSleepTime holds the string denoting the sleep_time field in the database.
	FieldSleepTime = "sleep_time"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldDailyIntake holds the string denoting the daily_intake field in the database.
	FieldDailyIntake = "daily_intake"
	// FieldContainerImage holds the string denoting the container_image field in the database.
	FieldContainerImage = "container_image"
	// FieldContainerVolume holds the string denoting the container_volume field in the database.
	FieldContainerVolume = "container_volume"
	// FieldDrinkAtATime holds the string denoting the drink_at_a_time field in the database.
	FieldDrinkAtATime = "drink_at_a_time"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUsername,
	FieldAvatar,
	FieldRemindMe,
	FieldWakeUpTime,
	FieldSleepTime,
	FieldGender,
	FieldWeight,
	FieldDailyIntake,
	FieldContainerImage,
	FieldContainerVolume,
	FieldDrinkAtATime,
	FieldPassword,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/ducnguyen96/ducnguyen96.xyz-apis/authservice/ent/runtime"
//
var (
	Hooks [1]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAvatar holds the default value on creation for the "avatar" field.
	DefaultAvatar string
	// DefaultRemindMe holds the default value on creation for the "remind_me" field.
	DefaultRemindMe bool
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight float32
	// DefaultDailyIntake holds the default value on creation for the "daily_intake" field.
	DefaultDailyIntake int32
	// DefaultContainerImage holds the default value on creation for the "container_image" field.
	DefaultContainerImage string
	// DefaultContainerVolume holds the default value on creation for the "container_volume" field.
	DefaultContainerVolume int32
	// DefaultDrinkAtATime holds the default value on creation for the "drink_at_a_time" field.
	DefaultDrinkAtATime int32
)

// GenderValidator is a validator for the "gender" field enum values. It is called by the builders before save.
func GenderValidator(ge schema.Gender) error {
	switch ge.String() {
	case "MALE", "FEMALE":
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for gender field: %q", ge)
	}
}
